# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            giorgio patrini
tagline:          'my personal webpage'
url:              http://giorgiopatrini.org
baseurl:          http://giorgiopatrini.org/

author:
  name:           'Giorgio Patrini'
  email:          'giorgio.patrini @ anu.edu.au'

paginate:         5

gems:
  - jekyll/scholar
  - jekyll-paginate

# jekyll-scholar config
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: _bibliography
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

kramdown:
  input: GFM

analytics :
  provider : google
  google :
      tracking_id : 'UA-55134574-1'

site:
  github_username: giorgiop
