# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            giorgio patrini
tagline:          'personal webpage'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://giorgiopatrini.org
baseurl:          /

author:
  name:           'Giorgio Patrini'
  email:          'au.edu.anu@patrini.giorgio [::-1]'

paginate:         5

gems:
  - jekyll/scholar
  - jekyll-paginate

# jekyll-scholar config
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: _bibliography
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

kramdown:
  input: GFM

analytics :
  provider : google
  google :
      tracking_id : 'UA-55134574-1'

site:
  github_username: giorgiop
