# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            giorgio patrini
tagline:          'my personal webpage'
url:              http://giorgiopatrini.org
baseurl:          http://giorgiopatrini.org/

author:
  name:           'Giorgio Patrini'
  email:          'g.patrini @ uva.nl'
  location:       'Amsterdam, Netherlands'

gems:
  - jekyll/scholar

# jekyll-scholar config
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: _bibliography
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

kramdown:
  input: GFM
  syntax_highlighter: rouge
fenced_code_blocks: true

analytics :
  provider : google
  google :
      tracking_id : 'UA-55134574-1'

site:
  github_username: giorgiop
